### ISSUE TITLE
Flush and rate limiting design

### ISSUE THREAD

**Issue by adlrocha** [ipld/go-storethehash#9]
@hannahhoward, can we have your input here? Thanks! 😊

While it does not need to block this PR, I would like to understand the design behind the flush mechanism and rate limiting.  It looks like `flushTick` does a sleep if the previous operation was sufficiently recent.  Why is that needed, instead of letting backpressure from the underlying storage provide rate limiting?

_Originally posted by @gammazero in https://github.com/ipld/go-storethehash/pull/6#discussion_r668288546_

**Comment by gammazero** [comment]
Storethehash tracks how fast data can be flushed to disk. When new data is being put into storethehash, a check is done to see:
- If the data is coming in faster than it can be flushed, and ...
- If the amount of data accumulated in memory, since the last flush, is more than some threshold (`BurstRate`).

When both of the above conditions are true, an immediate flush is triggered and that flush completion is waited on.

If data continues to come in at this rate, then even continuous flushes will not keep up. During each flush, more data will accumulate in memory than was flushed. The next flush will handle that larger amount of data, but will build up even data more in memory, and so on. At some point, storethehash needs to temporarily stop accepting more data, to allow flushes to catch up to what has built up in memory.
